### ISSUE TITLE
Upgrade to Junit 5

### ISSUE THREAD

**Issue by andonescu** [gwt-test-utils/gwt-test-utils#102]
Hi,

I will like to help with the upgrade to junit5, but I will like to know your opinion on how to proceed  : 

- upgrade `GwtTest` to use jupiter instead of junit
- create a parallel `Gwt5Test` class with the same functionality as `GwtTest` but upgraded to junit5

**Comment by nbartels** [comment]
I think there are a lot of projects out there, that are still using junit4. So I suggest providing junit5 in a Gwt5Test. gwt-test-utils should not force these projects to upgrade to junit5.

**Comment by ericjanmalotaux** [comment]
Any progress with this issue?

**Comment by andonescu** [comment]
Hi @ericjanmalotaux , I didn’t had the time to pursue this.  

Sorry,
