### ISSUE TITLE
Calling getClass() on a JavascriptObject throws NullpointerException.

### ISSUE THREAD

**Issue by Dominator008** [gwt-test-utils/gwt-test-utils#39]
Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk):

2.5.0

Encountered on OS / Browser (e.g. WinXP, IE9, FF10):

Using gwt-test-utils without a browser

Detailed description (please be as specific as possible):

Calling getClass() on a JavascriptObject throws NullpointerException.
The second setter cannot be invoked.

Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):

public class LineCharacter extends JavaScriptObject {
  public static LineCharacter create(int line, int ch) {
    LineCharacter lineCh = createObject().cast();
    return lineCh.setLine(line).setCh(ch); // The setter eventually invokes getClass() in GwtReflectionUtils.getPrivateFieldValue.
  }

  public final native LineCharacter setLine(int line) /*-{
    this.line = line; return this;
  }-*/;

  public final native LineCharacter setCh(int ch) /*-{
    this.ch = ch; return this;
  }-*/;
}

Stack trace:
java.lang.NullPointerException
        at com.googlecode.gwt.test.utils.GwtReflectionUtils.getPrivateFieldValue(GwtReflectionUtils.java:457)
        at com.googlecode.gwt.test.utils.JavaScriptObjects.getJsoProperties(JavaScriptObjects.java:107)
        at com.googlecode.gwt.test.utils.JavaScriptObjects.getJsoProperties(JavaScriptObjects.java:123)
        at com.googlecode.gwt.test.utils.JavaScriptObjects.getObject(JavaScriptObjects.java:55)
        at net.codemirror.lib.LineCharacter$.setCh$(LineCharacter.java)
        at net.codemirror.lib.LineCharacter$.create(LineCharacter.java:23)
        ...
Workaround if you have one:

Current workaround is to change the return type of the setters to "void", i.e.:
lineCh.setLine(line);
lineCh.setCh(ch);
return lineCh;

works. But this is not optimal.

**Comment by Gael** [comment]
In the case your setter does not respect the javabean getter/setter specification, gwt-test-utils will not be able to choose a proper implementation for the setter for you because it won't be able to guess what the setter should return.

You'll have to write your own LineCharacterPatcher class like this : 

```java
import com.googlecode.gwt.test.patchers.PatchClass;
import com.googlecode.gwt.test.patchers.PatchMethod;
import com.googlecode.gwt.test.utils.JavaScriptObjects;

@PatchClass(LineCharacter.class)
public class LineCharacterPatcher {

    @PatchMethod
    static LineCharacter setCh(LineCharacter lineCharacter, int ch) {
        JavaScriptObjects.setProperty(lineCharacter, "ch", ch);
        return lineCharacter;
    }

    @PatchMethod
    static LineCharacter setLine(LineCharacter lineCharacter, int line) {
        JavaScriptObjects.setProperty(lineCharacter, "line", line);
        return lineCharacter;
    }
}
```

Don't forget to register the package of your LineCharacterPatcher in gwt-test-utils.properties file : 

```
your.package.with.custom.patchers=scan-package
```
