### ISSUE TITLE
com.google.gwt.http.client.URL

### ISSUE THREAD

**Issue by wokier** [gwt-test-utils/gwt-test-utils#54]
Hi

It seems that URL is not available from gwt-test-utils tests

java.lang.UnsatisfiedLinkError: com.google.gwt.http.client.URL.decodeImpl(Ljava/lang/String;)Ljava/lang/String;
	at com.google.gwt.http.client.URL.decodeImpl(Native Method)
	at com.google.gwt.http.client.URL.decode(URL.java:41)
	at ...

**Comment by Gael** [comment]
After awhile, I fixed it in gwt-test-utils 0.52 for GWT 2.7. It will land on Maven Central in a few hours.
