### ISSUE TITLE
gwt 2.6.0

### ISSUE THREAD

**Issue by elacazed** [gwt-test-utils/gwt-test-utils#62]
Now that GWT 2.6.0 has been released, how can we expect a compatible release? 
I can try to help if you need it.

regards,

Etienne Lacazedieu

**Comment by EmteZogaf** [comment]
Is it possible to put support for GXT 2 back as [version 2.3.1a has been made compatible with GWT 2.6 ](http://www.sencha.com/forum/showthread.php?275759-GXT-2.2.6-2.3-with-GWT-2.6&p=1053247&viewfull=1#post1053247)?
