### ISSUE TITLE
Framework loads the wrong gwt-test-utils.properties

### ISSUE THREAD

**Issue by diskostu** [gwt-test-utils/gwt-test-utils#85]
I always get the error 

> com.googlecode.gwt.test.exceptions.GwtTestConfigurationException: No declared module. [...]

regardless of my code.
I debugged the class ConfigurationLoader:readFiles() and noticed that the class reads the gwt-test-utils.properties from your framework from the classpath. So it cannot find any of my modules.

Maybe this is a bug?

**Comment by Gael** [comment]
Every file META-INF/gwt-test-utils.properties are read.
See samples here : https://github.com/gwt-test-utils/gwt-test-utils-samples

Under maven classpath src/test/resources, there is a META-INF/gwt-test-utils.properties file with custom module defined. [Example there](https://github.com/gwt-test-utils/gwt-test-utils-samples/blob/master/sample/src/test/resources/META-INF/gwt-test-utils.properties)
