### ISSUE TITLE
AnimationSupportDetectorPatcher not working

### ISSUE THREAD

**Issue by benjob** [gwt-test-utils/gwt-test-utils#97]
Hi,

First I would like to mention that I have very little experience with GWT and gwt-test-utils so I may be using it improperly but I believe there is an issue with AnimationSupportDetectorPatcher.

The builtin patcher is here:
https://github.com/gwt-test-utils/gwt-test-utils/blob/master/gwt-test-utils/src/main/java/com/googlecode/gwt/test/internal/patchers/AnimationSupportDetectorPatcher.java

This is to patch AnimationScheduler.AnimationSupportDetector:
http://www.gwtproject.org/javadoc/latest/com/google/gwt/animation/client/AnimationScheduler.AnimationSupportDetector.html

I believe the problem is with the PatchClass annotation. With this value, the patchClassMap will name the class: 
com.google.gwt.animation.client.AnimationScheduler.AnimationSupportDetector

But AnimationSupportDetector is an inner class of AnimationScheduler.

GwtClassLoader is requested to load the class with the following name:
com.google.gwt.animation.client.AnimationScheduler$AnimationSupportDetector

as opposed to:
com.google.gwt.animation.client.AnimationScheduler.AnimationSupportDetector

Which means that the class will not be patched and an invocation on AnimationScheduler.AnimationSupportDetector.isNativelySupported() will return a java.lang.UnsatisfiedLinkError

I confirm that, if I change AnimationSupportDetectorPatcher with the following code the error goes away (note the PatchClass annotation):

```
package com.googlecode.gwt.test.internal.patchers;
  
import com.google.gwt.animation.client.AnimationScheduler.AnimationSupportDetector;
import com.googlecode.gwt.test.patchers.PatchClass;
import com.googlecode.gwt.test.patchers.PatchMethod;

@PatchClass(target = "com.google.gwt.animation.client.AnimationScheduler$AnimationSupportDetector")
public class AnimationSupportDetectorPatcher {

    @PatchMethod
    static boolean isNativelySupported(AnimationSupportDetector detector) {
        return false;
    }

}
```

Like I said, I just have a few days of experience with GWT and gwt-test-utils so maybe I am using the framework wrong but looking at the other patchers (for inner classes) it does feel like there is an issue. These other patchers do use the proper inner class name:

https://github.com/gwt-test-utils/gwt-test-utils/blob/master/gwt-test-utils/src/main/java/com/googlecode/gwt/test/internal/patchers/ListWrapperPatcher.java

Hope it helps,
Benjamin.

**Comment by benjob** [comment]
Just to give an update: using javassist 3.19.0 or above also fixes the problem without having to re-define the Patcher.

**Comment by nbartels** [comment]
Many thanks for the information and the analyses. Updating javassist should be a good idea and we will check this soon.

**Comment by benjob** [comment]
Actually gwt-test-utils is fine, you are already using 3.21.0-GA
I hit this issue because the project I am working on is using an older version of gwt-test-utils (0.53) which I believe did have this problem. I haven't tried but I believe the latest version of gwt-test-utils does not have this problem. I believe it is more a problem on my side than yours.
Thanks a lot!
